server:
  port: 8010
spring:
  redis:
    database: 0
    host: 47.97.112.225
    port: 6379
    password: ''
    timeout: 10000
    block-when-exhausted: true
    jedis:
      pool:
        max-wait: 10000
        max-idle: 200
        min-idle: 0
        max-active: 1024

prop:
  redis:
    default_db: 0
